-- Seed Categories for VIP Reseller Integration
-- Uses ON CONFLICT to upsert based on Slug

INSERT INTO "categories" ("id", "name", "slug", "code", "image", "requiresZoneId", "requiresServerId", "profitMargin", "isActive", "updatedAt") VALUES
-- Mobile Legends
(gen_random_uuid(), 'Mobile Legends', 'mobile-legends', 'mobile-legends', 'https://upload.wikimedia.org/wikipedia/en/2/26/Mobile_Legends_Bang_Bang_logo.png', true, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Mobile Legends (Global)', 'mobile-legends-global', 'mobile-legends', 'https://upload.wikimedia.org/wikipedia/en/2/26/Mobile_Legends_Bang_Bang_logo.png', true, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Mobile Legends (Malaysia)', 'mobile-legends-malaysia', 'mobile-legends', 'https://upload.wikimedia.org/wikipedia/en/2/26/Mobile_Legends_Bang_Bang_logo.png', true, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Mobile Legends (Philippines)', 'mobile-legends-philippines', 'mobile-legends', 'https://upload.wikimedia.org/wikipedia/en/2/26/Mobile_Legends_Bang_Bang_logo.png', true, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Mobile Legends (Singapore)', 'mobile-legends-singapore', 'mobile-legends', 'https://upload.wikimedia.org/wikipedia/en/2/26/Mobile_Legends_Bang_Bang_logo.png', true, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Mobile Legends (Brazil)', 'mobile-legends-brazil', 'mobile-legends', 'https://upload.wikimedia.org/wikipedia/en/2/26/Mobile_Legends_Bang_Bang_logo.png', true, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Mobile Legends (Russia)', 'mobile-legends-russia', 'mobile-legends', 'https://upload.wikimedia.org/wikipedia/en/2/26/Mobile_Legends_Bang_Bang_logo.png', true, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Mobile Legends A', 'mobile-legends-a', 'mobile-legends', 'https://upload.wikimedia.org/wikipedia/en/2/26/Mobile_Legends_Bang_Bang_logo.png', true, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Mobile Legends B', 'mobile-legends-b', 'mobile-legends', 'https://upload.wikimedia.org/wikipedia/en/2/26/Mobile_Legends_Bang_Bang_logo.png', true, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Mobile Legends Gift', 'mobile-legends-gift', 'mobile-legends', 'https://upload.wikimedia.org/wikipedia/en/2/26/Mobile_Legends_Bang_Bang_logo.png', true, false, 5.0, true, NOW()),

-- Free Fire
(gen_random_uuid(), 'Free Fire', 'free-fire', 'free-fire', 'https://upload.wikimedia.org/wikipedia/en/a/a2/Free_Fire_logo.png', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Free Fire Max', 'free-fire-max', 'free-fire-max', 'https://upload.wikimedia.org/wikipedia/en/a/a2/Free_Fire_logo.png', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Free Fire Global', 'free-fire-global', 'free-fire', 'https://upload.wikimedia.org/wikipedia/en/a/a2/Free_Fire_logo.png', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Free Fire Max Global', 'free-fire-max-global', 'free-fire-max', 'https://upload.wikimedia.org/wikipedia/en/a/a2/Free_Fire_logo.png', false, false, 5.0, true, NOW()),

-- PUBG & FPS
(gen_random_uuid(), 'PUBG Mobile (GLOBAL)', 'pubg-mobile-global', 'pubg-mobile-global', 'https://upload.wikimedia.org/wikipedia/en/0/01/PUBG_Mobile_app_icon.png', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'PUBG Mobile (ID)', 'pubg-mobile-id', 'PUBG Mobile (ID)', 'https://upload.wikimedia.org/wikipedia/en/0/01/PUBG_Mobile_app_icon.png', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'PUBG : New State Mobile', 'pubg-new-state-mobile', 'PUBG : New State Mobile', 'https://upload.wikimedia.org/wikipedia/en/thumb/2/21/PUBG_New_State_logo.svg/1200px-PUBG_New_State_logo.svg.png', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Call of Duty Mobile (Indonesia)', 'call-of-duty-mobile-indonesia', 'call-of-duty-mobile', 'https://upload.wikimedia.org/wikipedia/en/3/3a/Call_of_Duty_Mobile_logo.png', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Call of Duty MOBILE', 'call-of-duty-mobile', 'call-of-duty-mobile', 'https://upload.wikimedia.org/wikipedia/en/3/3a/Call_of_Duty_Mobile_logo.png', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Valorant', 'valorant', 'valorant', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Valorant_logo_-_pink_color_version.svg/1200px-Valorant_logo_-_pink_color_version.svg.png', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Point Blank', 'point-blank', 'point-blank', 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Point_Blank_Logo.png', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Blood Strike', 'blood-strike', 'Blood Strike', 'https://placehold.co/400?text=Blood+Strike', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Arena Breakout', 'arena-breakout', 'Arena Breakout', 'https://placehold.co/400?text=Arena+Breakout', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Arena Breakout: Infinite (PC)', 'arena-breakout-infinite-pc', 'Arena Breakout: Infinite (PC)', 'https://placehold.co/400?text=Arena+Breakout', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Delta Force', 'delta-force', 'Delta Force', 'https://placehold.co/400?text=Delta+Force', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Farlight 84', 'farlight-84', 'Farlight 84', 'https://upload.wikimedia.org/wikipedia/en/a/a6/Farlight_84_Logo.png', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Sausage Man', 'sausage-man', 'Sausage Man', 'https://placehold.co/400?text=Sausage+Man', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Super Sus', 'super-sus', 'Super Sus', 'https://placehold.co/400?text=Super+Sus', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Metal Slug Awakening', 'metal-slug-awakening', 'Metal Slug Awakening', 'https://placehold.co/400?text=Metal+Slug', true, false, 5.0, true, NOW()),

-- RPG / Open World
(gen_random_uuid(), 'Genshin Impact', 'genshin-impact', 'genshin-impact', 'https://upload.wikimedia.org/wikipedia/en/5/5d/Genshin_Impact_logo.svg', true, true, 3.0, true, NOW()), 
(gen_random_uuid(), 'Honkai Impact 3', 'honkai-impact-3', 'Honkai Impact 3', 'https://upload.wikimedia.org/wikipedia/en/e/ee/Honkai-Impact-3rd-Logo.png', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Honkai Star Rail', 'honkai-star-rail', 'Honkai Star Rail', 'https://upload.wikimedia.org/wikipedia/en/thumb/9/91/Honkai_Star_Rail_logo.png/600px-Honkai_Star_Rail_logo.png', true, true, 3.0, true, NOW()),
(gen_random_uuid(), 'Zenless Zone Zero (ZZZ)', 'zenless-zone-zero', 'Zenless Zone Zero (ZZZ)', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Zenless_Zone_Zero_logo.svg/1200px-Zenless_Zone_Zero_logo.svg.png', true, true, 5.0, true, NOW()),
(gen_random_uuid(), 'Ragnarok M', 'ragnarok-m-eternal-love-big-cat-coin', 'ragnarok-m-eternal-love-big-cat-coin', 'https://placehold.co/400?text=Ragnarok+M', true, true, 5.0, true, NOW()),
(gen_random_uuid(), 'Ragnarok M Eternal Love (SEA)', 'ragnarok-m-eternal-love-sea', 'ragnarok-m-eternal-love-big-cat-coin', 'https://placehold.co/400?text=Ragnarok+M', true, true, 5.0, true, NOW()),
(gen_random_uuid(), 'Ragnarok Origin', 'ragnarok-origin', 'Ragnarok Origin', 'https://placehold.co/400?text=Ragnarok+Origin', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'RagnaroK X Next Generation', 'ragnarok-x-next-generation', 'RagnaroK X Next Generation', 'https://placehold.co/400?text=Ragnarok+X', true, true, 5.0, true, NOW()),
(gen_random_uuid(), 'Dragon Raja', 'dragon-raja', 'dragon-raja', 'https://placehold.co/400?text=Dragon+Raja', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Dragonheir Silent Gods', 'dragonheir-silent-gods', 'Dragonheir Silent Gods', 'https://placehold.co/400?text=Dragonheir', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'LifeAfter', 'lifeafter', 'LifeAfter', 'https://placehold.co/400?text=LifeAfter', true, true, 5.0, true, NOW()),
(gen_random_uuid(), 'Light of Thel: New Era', 'light-of-thel-new-era', 'Light of Thel: New Era', 'https://placehold.co/400?text=Light+of+Thel', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Astral Guardians: Cyber Fantasy', 'astral-guardians-cyber-fantasy', 'Astral Guardians: Cyber Fantasy', 'https://placehold.co/400?text=Astral+Guardians', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Watcher Of Realms', 'watcher-of-realms', 'Watcher Of Realms', 'https://placehold.co/400?text=Watcher+of+Realms', true, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Whiteout Survival', 'whiteout-survival', 'Whiteout Survival', 'https://placehold.co/400?text=Whiteout+Survival', false, false, 5.0, true, NOW()),

-- MOBA / Strategy
(gen_random_uuid(), 'League of Legends: Wild Rift', 'league-of-legends-wild-rift', 'league-of-legends-wild-rift', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/League_of_Legends_Wild_Rift_logo.svg/1200px-League_of_Legends_Wild_Rift_logo.svg.png', true, false, 5.0, true, NOW()),
(gen_random_uuid(), 'League of Legends', 'league-of-legends', 'League of Legends', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/League_of_Legends_2019_vector.svg/1200px-League_of_Legends_2019_vector.svg.png', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Arena of Valor', 'arena-of-valor', 'arena-of-valor', 'https://upload.wikimedia.org/wikipedia/en/thumb/0/07/Arena_of_Valor.png/220px-Arena_of_Valor.png', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Honor of Kings Global', 'honor-of-kings-global', 'Honor of Kings Global', 'https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Honor_of_Kings_Logo.png/220px-Honor_of_Kings_Logo.png', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Marvel Super War', 'marvel-super-war', 'marvel-super-war', 'https://placehold.co/400?text=Marvel+Super+War', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Marvel Rivals', 'marvel-rivals', 'Marvel Rivals', 'https://placehold.co/400?text=Marvel+Rivals', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Marvel Duel', 'marvel-duel', 'Marvel Duel', 'https://placehold.co/400?text=Marvel+Duel', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Auto Chess', 'auto-chess', 'auto-chess', 'https://placehold.co/400?text=Auto+Chess', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Magic Chess: Go Go', 'magic-chess-go-go', 'Magic Chess: Go Go', 'https://placehold.co/400?text=Magic+Chess', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Magic Chess: Go Go (Global)', 'magic-chess-go-go-global', 'magic-chess-go-go', 'https://placehold.co/400?text=Magic+Chess', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Clash of Clans', 'clash-of-clans', 'Clash of Clans', 'https://upload.wikimedia.org/wikipedia/en/thumb/5/59/Clash_of_Clans_Logo.png/220px-Clash_of_Clans_Logo.png', true, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Clash Royale', 'clash-royale', 'Clash Royale', 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c1/Clash_Royale_logo.png/220px-Clash_Royale_logo.png', true, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Brawl Stars', 'brawl-stars', 'Brawl Stars', 'https://upload.wikimedia.org/wikipedia/en/thumb/2/27/Brawl_Stars_logo.png/220px-Brawl_Stars_logo.png', true, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Lords Mobile', 'lords-mobile', 'lords-mobile', 'https://placehold.co/400?text=Lords+Mobile', true, false, 5.0, true, NOW()),
(gen_random_uuid(), 'State of Survival: Zombie War', 'state-of-survival-zombie-war', 'State of Survival: Zombie War', 'https://placehold.co/400?text=State+of+Survival', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Age of Empires Mobile', 'age-of-empires-mobile', 'Age of Empires Mobile', 'https://placehold.co/400?text=Age+of+Empires', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Castle Duels', 'castle-duels', 'Castle Duels', 'https://placehold.co/400?text=Castle+Duels', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'King of Avalon', 'king-of-avalon', 'King of Avalon', 'https://placehold.co/400?text=King+of+Avalon', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'King Of Avalon', 'king-of-avalon-duplicate', 'King Of Avalon', 'https://placehold.co/400?text=King+of+Avalon', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Dynasty Warriors: Overlords', 'dynasty-warriors-overlords', 'Dynasty Warriors: Overlords', 'https://placehold.co/400?text=Dynasty+Warriors', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Conquer Online (Point Card)', 'conquer-online-point-card', 'Conquer Online (Point Card)', 'https://placehold.co/400?text=Conquer+Online', false, false, 5.0, true, NOW()),

-- Casual / Others
(gen_random_uuid(), 'Higgs Domino', 'higgs-domino', 'higgs-domino', 'https://placehold.co/400?text=Higgs+Domino', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Domino Gaple Boyaa Qiuqiu', 'domino-gaple-qiuqiu-boyaa', 'domino-gaple-qiuqiu-boyaa', 'https://placehold.co/400?text=Domino+Gaple', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Hago', 'hago', 'hago', 'https://placehold.co/400?text=Hago', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Ludo Club', 'ludo-club', 'Ludo Club', 'https://placehold.co/400?text=Ludo+Club', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Zepeto', 'zepeto', 'zepeto', 'https://placehold.co/400?text=Zepeto', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Roblox Via Login', 'roblox-via-login', 'Roblox Via Login', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Roblox_Logo_2022.svg/1200px-Roblox_Logo_2022.svg.png', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Growtopia', 'growtopia', 'Growtopia', 'https://placehold.co/400?text=Growtopia', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Eggy Party', 'eggy-party', 'Eggy Party', 'https://placehold.co/400?text=Eggy+Party', true, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Identity V', 'identity-v', 'Identity V', 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/Identity_V.jpg/220px-Identity_V.jpg', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Love and Deepspace', 'love-and-deepspace', 'Love and Deepspace', 'https://placehold.co/400?text=Love+and+Deepspace', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Likee', 'likee', 'Likee', 'https://placehold.co/400?text=Likee', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Ace Racer', 'ace-racer', 'Ace Racer', 'https://placehold.co/400?text=Ace+Racer', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Speed Drifters', 'speed-drifters', 'speed-drifters', 'https://placehold.co/400?text=Speed+Drifters', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'AFK Journey', 'afk-journey', 'AFK Journey', 'https://placehold.co/400?text=AFK+Journey', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Be The King', 'be-the-king', 'Be The King', 'https://placehold.co/400?text=Be+The+King', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Football Master 2', 'football-master-2', 'Football Master 2', 'https://placehold.co/400?text=Football+Master', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'EA SPORTS FC Mobile', 'ea-sports-fc-mobile', 'EA SPORTS FC Mobile', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/EA_Sports_FC_Mobile_logo.svg/1200px-EA_Sports_FC_Mobile_logo.svg.png', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'NBA Infinite (Europe)', 'nba-infinite-europe', 'NBA Infinite (Europe)', 'https://placehold.co/400?text=NBA+Infinite', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'One Punch Man', 'one-punch-man', 'One Punch Man', 'https://placehold.co/400?text=One+Punch+Man', true, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Laplace M', 'laplace-m', 'laplace-m', 'https://placehold.co/400?text=Laplace+M', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Tom and Jerry:chase', 'tom-and-jerry-chase', 'tom-and-jerry-chase', 'https://placehold.co/400?text=Tom+and+Jerry', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Tom and Jerry Chase', 'tom-and-jerry-chase-duplicate', 'Tom and Jerry Chase', 'https://placehold.co/400?text=Tom+and+Jerry', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Cocofun', 'cocofun', 'cocofun', 'https://placehold.co/400?text=Cocofun', false, false, 5.0, true, NOW()),
(gen_random_uuid(), '8 Ball Pool', '8-ball-pool', '8-ball-pool', 'https://placehold.co/400?text=8+Ball+Pool', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Bullet Angel', 'bullet-angel', 'bullet-angel', 'https://placehold.co/400?text=Bullet+Angel', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'IndoPlay', 'indoplay', 'indoplay', 'https://placehold.co/400?text=IndoPlay', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Garena Undawn', 'garena-undawn', 'Garena Undawn', 'https://placehold.co/400?text=Garena+Undawn', true, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Revelation Infinite Journey', 'revelation-infinite-journey', 'Revelation Infinite Journey', 'https://placehold.co/400?text=Revelation', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Infinite Borders', 'infinite-borders', 'Infinite Borders', 'https://placehold.co/400?text=Infinite+Borders', false, false, 5.0, true, NOW()),
(gen_random_uuid(), 'Warp Plus', 'warp-plus', 'Warp Plus', 'https://placehold.co/400?text=Warp+Plus', false, false, 5.0, true, NOW()),

-- Vouchers
(gen_random_uuid(), 'Steam Wallet Code', 'steam-wallet-code', 'Steam Wallet Code', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Steam_icon_logo.svg/1200px-Steam_icon_logo.svg.png', false, false, 2.0, true, NOW()),
(gen_random_uuid(), 'Voucher Garena Shell', 'voucher-garena-shell', 'Voucher Garena Shell', 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d5/Garena_logo.svg/1200px-Garena_logo.svg.png', false, false, 2.0, true, NOW()),
(gen_random_uuid(), 'Voucher Megaxus', 'voucher-megaxus', 'Voucher Megaxus', 'https://placehold.co/400?text=Megaxus', false, false, 2.0, true, NOW()),
(gen_random_uuid(), 'Voucher PB Zepetto', 'voucher-pb-zepetto', 'Voucher PB Zepetto', 'https://placehold.co/400?text=PB+Zepetto', false, false, 2.0, true, NOW()),
(gen_random_uuid(), 'Voucher PSN', 'voucher-psn', 'Voucher PSN', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/PlayStation_logo.svg/1200px-PlayStation_logo.svg.png', false, false, 2.0, true, NOW()),
(gen_random_uuid(), 'Voucher Razer Gold', 'voucher-razer-gold', 'Voucher Razer Gold', 'https://placehold.co/400?text=Razer+Gold', false, false, 2.0, true, NOW()),
(gen_random_uuid(), 'Voucher Roblox', 'voucher-roblox', 'Voucher Roblox', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Roblox_Logo_2022.svg/1200px-Roblox_Logo_2022.svg.png', false, false, 2.0, true, NOW()),
(gen_random_uuid(), 'Voucher Valorant', 'voucher-valorant', 'Voucher Valorant', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Valorant_logo_-_pink_color_version.svg/1200px-Valorant_logo_-_pink_color_version.svg.png', false, false, 2.0, true, NOW())

ON CONFLICT ("slug") DO UPDATE SET
  "name" = EXCLUDED."name",
  "code" = EXCLUDED."code",
  "image" = EXCLUDED."image",
  "requiresZoneId" = EXCLUDED."requiresZoneId",
  "requiresServerId" = EXCLUDED."requiresServerId",
  "profitMargin" = EXCLUDED."profitMargin",
  "updatedAt" = NOW();
